"""Initial migration

Revision ID: 61bbaf715bc6
Revises:
Create Date: 2025-07-25 19:28:18.895957

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61bbaf715bc6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("num_reviews", sa.Integer(), nullable=False),
        sa.Column("review_cursor", sa.String(), nullable=True),
        sa.Column("review_score", sa.Integer(), nullable=False),
        sa.Column("review_score_desc", sa.String(), nullable=False),
        sa.Column("total_positive", sa.Integer(), nullable=False),
        sa.Column("total_negative", sa.Integer(), nullable=False),
        sa.Column("total_reviews", sa.Integer(), nullable=False),
        sa.Column("last_scraped", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_review_cursor"), "game", ["review_cursor"], unique=False
    )
    op.create_table(
        "user",
        sa.Column("steamid", sa.String(), nullable=False),
        sa.Column("num_games_owned", sa.Integer(), nullable=False),
        sa.Column("num_reviews", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("steamid"),
    )
    op.create_table(
        "review",
        sa.Column("recommendationid", sa.String(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("author_steamid", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("review_text", sa.String(), nullable=False),
        sa.Column("timestamp_created", sa.BigInteger(), nullable=False),
        sa.Column("timestamp_updated", sa.BigInteger(), nullable=False),
        sa.Column("voted_up", sa.Boolean(), nullable=False),
        sa.Column("votes_up", sa.Integer(), nullable=False),
        sa.Column("votes_funny", sa.Integer(), nullable=False),
        sa.Column("weighted_vote_score", sa.Float(), nullable=False),
        sa.Column("comment_count", sa.Integer(), nullable=False),
        sa.Column("steam_purchase", sa.Boolean(), nullable=False),
        sa.Column("received_for_free", sa.Boolean(), nullable=False),
        sa.Column("written_during_early_access", sa.Boolean(), nullable=False),
        sa.Column("primarily_steam_deck", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_steamid"],
            ["user.steamid"],
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game.id"],
        ),
        sa.PrimaryKeyConstraint("recommendationid"),
    )
    op.create_table(
        "usergamestat",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("playtime_forever", sa.BigInteger(), nullable=False),
        sa.Column("playtime_last_two_weeks", sa.BigInteger(), nullable=False),
        sa.Column("last_played", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.steamid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usergamestat")
    op.drop_table("review")
    op.drop_table("user")
    op.drop_index(op.f("ix_game_review_cursor"), table_name="game")
    op.drop_table("game")
    # ### end Alembic commands ###
